# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - "*"
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
    - title: Enhancements
      labels:
        - enhancement
    - title: Bugfixes
      labels:
        - bug       
    - title: Internal Tasks
      labels:
        - "*"
        
